language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


before_deploy:
  - mkdir -p deploy
  - zip - r springboot-aws-web-service *
  - mv springboot-aws-web-service.zip deploy/springboot-aws-web-service.zip

deploy:
  - provider: s3
    access_key_id: AKIA4WBOXOKK6AUNOTEM
    secret_access_key: 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
    bucket: sbaws-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - sungsik.yang92@gmail.com
